// examples/vue-router/src/pages/about.vue
<script setup lang="ts">
import { useTimeAgo } from '@vueuse/core'
import { useRouter } from 'vue-router'

// replaced dyanmicaly
const date = '__DATE__'
const timeAgo = useTimeAgo(date)
const router = useRouter()
</script>

<template>
  <div>About route, built at: {{ date }} ({{ timeAgo }})</div>
  <br>
  <button @click="router.push('/')">
    Home
  </button>
</template>

// examples/solid-router/src/pages/about.tsx
import { Link } from '@solidjs/router'

export default function About() {
  // replaced dyanmicaly
  const date = '__DATE__'

  return (
    <div>
      <div>
        <strong>/about</strong>
        {' '}
        route, built at:
        {' '}
        { date }
      </div>
      <br />
      <Link href="/">
        Go Home
      </Link>
    </div>
  )
}
