// examples/react-router/src/pages/Home.tsx
import React, { useState } from 'react'
import { useNavigate } from 'react-router'
import './Home.css'

function Home() {
  const [count, setCount] = useState(0)

  const [name, setName] = useState('')

  const router = useNavigate()

  // @ts-expect-error just ignore
  const handleChange = (event) => {
    setName(event.target.value || '')
  }

  // @ts-expect-error just ignore
  const handleSubmit = (event) => {
    event.preventDefault()
    if (name)
      router(`/hi/${name}`)
  }

  return (
    <div className="Home">
      <p>
        <button type="button" onClick={() => setCount(count => count + 1)}>
          count is:
          {' '}
          {count}
        </button>
      </p>
      <br />
      <form onSubmit={handleSubmit}>
        <input value={name} onChange={handleChange} type="text" aria-label="What's your name?" placeholder="What's your name?" />
        <button type="submit">GO</button>
      </form>
      <br />
      <a href="/about">About</a>
      <br />
    </div>
  )
}

export default Home

// examples/solid-router/src/pages/home.tsx
import { useNavigate } from '@solidjs/router'
import { createSignal } from 'solid-js'
import styles from './home.module.css'

export default function Home() {
  const navigate = useNavigate()
  const [count, setCount] = createSignal(0)
  const [name, setName] = createSignal('')

  const handleChange = (event) => {
    setName(event.target.value || '')
  }

  const handleSubmit = (event) => {
    event.preventDefault()
    const submit = name()
    if (submit && submit.trim().length > 0)
      navigate(`/hi/${submit}`)
  }

  return (
    <div class={styles.Home}>
      <p>
        <button type="button" onClick={() => setCount(count() + 1)}>
          count is:
          {' '}
          {count}
        </button>
      </p>
      <br />
      <form onSubmit={handleSubmit}>
        <input value={name()} onChange={handleChange} type="text" aria-label="What's your name?" placeholder="What's your name?" />
        <button type="submit">GO</button>
      </form>
      <br />
      <a href="/about">About</a>
      <br />
    </div>
  )
}
