// examples/vue-basic/src/App.vue
<script setup lang="ts">
import { useTimeAgo } from '@vueuse/core'
import ReloadPrompt from './ReloadPrompt.vue'

// replaced dyanmicaly
const date = '__DATE__'
const timeAgo = useTimeAgo(date)
</script>

<template>
  <img src="/favicon.svg" alt="PWA Logo" width="60" height="60" />
  <div>Built at: {{ date }} ({{ timeAgo }})</div>
  <ReloadPrompt />
</template>

// examples/react-router/src/App.tsx
import React from 'react'
import { Outlet } from 'react-router-dom'
import ReloadPrompt from './ReloadPrompt'
import './App.css'

function App() {
  // replaced dyanmicaly
  const date = '__DATE__'

  return (
    <main className="App">
      <img src="/favicon.svg" alt="PWA Logo" width="60" height="60" />
      <h1 className="Home-title">PWA React!</h1>
      <div className="Home-built">
        Built at:
        {date}
      </div>
      <Outlet />
      <ReloadPrompt />
    </main>
  )
}

export default App
