// examples/solid-router/src/app.tsx
import type { Component } from 'solid-js'
import { useRoutes } from '@solidjs/router'
import { routes } from './routes'
import styles from './app.module.css'
import ReloadPrompt from './ReloadPrompt'

const App: Component = () => {
  // replaced dynamically
  const date = '__DATE__'

  const Route = useRoutes(routes)

  return (
    <main class={styles.App}>
      <img src="/favicon.svg" alt="PWA Logo" width="60" height="60" />
      <h1 class={styles.Title}>PWA SolidJS!</h1>
      <div class={styles.Built}>
        Built at:
        {date}
      </div>
      <Route />
      <ReloadPrompt />
    </main>
  )
}

export default App

// examples/react-router/src/App.tsx
import React from 'react'
import { Outlet } from 'react-router-dom'
import ReloadPrompt from './ReloadPrompt'
import './App.css'

function App() {
  // replaced dyanmicaly
  const date = '__DATE__'

  return (
    <main className="App">
      <img src="/favicon.svg" alt="PWA Logo" width="60" height="60" />
      <h1 className="Home-title">PWA React!</h1>
      <div className="Home-built">
        Built at:
        {date}
      </div>
      <Outlet />
      <ReloadPrompt />
    </main>
  )
}

export default App
