// examples/preact-router/src/pages/About.tsx
function About() {
  // replaced dyanmicaly
  const date = '__DATE__'
  return (
    <div className="About">
      <div>
        <strong>/about</strong>
        {' '}
        route, built at:
        {' '}
        { date }
      </div>
      <br />
      <a href="/">Go Home</a>
    </div>
  )
}

export default About

// examples/vue-router/src/pages/about.vue
<script setup lang="ts">
import { useTimeAgo } from '@vueuse/core'
import { useRouter } from 'vue-router'

// replaced dyanmicaly
const date = '__DATE__'
const timeAgo = useTimeAgo(date)
const router = useRouter()
</script>

<template>
  <div>About route, built at: {{ date }} ({{ timeAgo }})</div>
  <br>
  <button @click="router.push('/')">
    Home
  </button>
</template>
