// examples/solid-router/src/app.tsx
import type { Component } from 'solid-js'
import { useRoutes } from '@solidjs/router'
import { routes } from './routes'
import styles from './app.module.css'
import ReloadPrompt from './ReloadPrompt'

const App: Component = () => {
  // replaced dynamically
  const date = '__DATE__'

  const Route = useRoutes(routes)

  return (
    <main class={styles.App}>
      <img src="/favicon.svg" alt="PWA Logo" width="60" height="60" />
      <h1 class={styles.Title}>PWA SolidJS!</h1>
      <div class={styles.Built}>
        Built at:
        {date}
      </div>
      <Route />
      <ReloadPrompt />
    </main>
  )
}

export default App

// examples/preact-router/src/app.tsx
import { Router } from 'preact-router'

import ReloadPrompt from './ReloadPrompt'
import Home from './pages/Home'
import About from './pages/About'
import Hi from './pages/hi/[name]'

import './App.css'

export function App() {
  // replaced dyanmicaly
  const date = '__DATE__'
  return (
    <>
      <main className="App">
        <img src="/favicon.svg" alt="PWA Logo" width="60" height="60" />
        <h1 className="Home-title">PWA Preact!</h1>
        <div className="Home-built">Built at: {date}</div>
        <Router>
          <Home default path="/" />
          <About path="/about" />
          <Hi path="/hi/:name" />
        </Router>
        <ReloadPrompt />
      </main>
    </>
  )
}
