// examples/preact-router/src/pages/hi/[name].tsx
import type { RouteProps } from 'preact-router'

function Hi(props: RouteProps<{ name: string }>) {
  // replaced dyanmicaly
  const date = '__DATE__'
  return (
    <div>
      <div><strong>/hi</strong> route, built at: { date }</div>
      <p>Hi: { props.name }</p>
      <br />
      <a href="/">Go Home</a>
    </div>
  )
}

export default Hi

// examples/svelte-routify/src/pages/hi/[name].svelte
<script lang="ts">
  import { url, params } from '@roxi/routify'

  // replaced dyanmicaly
  const date = '__DATE__'

  $: name = decodeURIComponent($params.name || '')
</script>

<div><strong>/hi</strong> route, built at: { date }</div>

<p>
  Hi: { name }
</p>
<br>
<a href={$url('../')}>Go Home</a>
