// examples/solid-router/src/pages/hi/[name].tsx
import { Link, useRouteData } from '@solidjs/router'

export default function Hi() {
  // replaced dyanmicaly
  const date = '__DATE__'
  const data: { name: string } = useRouteData()

  return (
    <div>
      <div>
        <strong>/hi</strong>
        {' '}
        route, built at:
        {' '}
        { date }
      </div>
      <p>
        Hi:
        { data.name }
      </p>
      <br />
      <Link href="/">
        Go Home
      </Link>
    </div>
  )
}

// examples/svelte-routify/src/pages/hi/[name].svelte
<script lang="ts">
  import { url, params } from '@roxi/routify'

  // replaced dyanmicaly
  const date = '__DATE__'

  $: name = decodeURIComponent($params.name || '')
</script>

<div><strong>/hi</strong> route, built at: { date }</div>

<p>
  Hi: { name }
</p>
<br>
<a href={$url('../')}>Go Home</a>
