// examples/react-router/src/pages/hi/[name].tsx
import React from 'react'
import { useParams } from 'react-router'

function Hi() {
  // replaced dyanmicaly
  const date = '__DATE__'
  const params = useParams()
  return (
    <div>
      <div><strong>/hi</strong> route, built at: { date }</div>
      <p>Hi: { params.name }</p>
      <br />
      <a href="/">Go Home</a>
    </div>
  )
}

export default Hi

// examples/svelte-routify/src/pages/hi/[name].svelte
<script lang="ts">
  import { url, params } from '@roxi/routify'

  // replaced dyanmicaly
  const date = '__DATE__'

  $: name = decodeURIComponent($params.name || '')
</script>

<div><strong>/hi</strong> route, built at: { date }</div>

<p>
  Hi: { name }
</p>
<br>
<a href={$url('../')}>Go Home</a>
