// examples/vue-router/src/pages/home.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useTimeAgo } from '@vueuse/core'
import { useRouter } from 'vue-router'

// replaced dynamically
const date = '__DATE__'
const timeAgo = useTimeAgo(date)
const router = useRouter()
const name = ref('')

function go() {
  if (name.value)
    router.push(`/hi/${encodeURIComponent(name.value)}`)
}
</script>

<template>
  <div>Home route, built at: {{ date }} ({{ timeAgo }})</div>
  <br>
  <form @submit.prevent="go">
    <input v-model="name" type="text" aria-label="What's your name?" placeholder="What's your name?">
    <br>
    <br>
    <button type="submit">
      GO
    </button>
  </form>
  <br>
  <button type="button" @click="router.push('/about')">
    About
  </button>
</template>

// examples/preact-router/src/pages/Home.tsx
import { useState } from 'preact/hooks'
import { route } from 'preact-router'
import './Home.css'

function Home() {
  const [count, setCount] = useState(0)

  const [name, setName] = useState('')

  // @ts-expect-error just ignore
  const handleChange = (event) => {
    setName(event.target.value || '')
  }

  // @ts-expect-error just ignore
  const handleSubmit = (event) => {
    event.preventDefault()
    if (name)
      route(`/hi/${name}`)
  }

  return (
    <div className="Home">
      <p>
        <button type="button" onClick={() => setCount(count => count + 1)}>
            count is: {count}
        </button>
      </p>
      <br />
      <form onSubmit={handleSubmit}>
        <input value={name} onChange={handleChange} type="text" aria-label="What's your name?" placeholder="What's your name?" />
        <button type="submit">GO</button>
      </form>
      <br/>
      <a href="/about">About</a>
      <br/>
    </div>
  )
}

export default Home
